 server:
    port: 8087

  spring:
    application:
      name: notification-service

    datasource:
      url: jdbc:mysql://localhost:3306/revcart_notification?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: YOUR_MYSQL_PASSWORD
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

  eureka:
    client:
      enabled: false

  jwt:
    secret: YOUR_JWT_SECRET
    expiration: 3600000

  logging:
    level:
      com.revature.notificationservice: DEBUG